# Generated by Django 2.2.3 on 2019-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190801_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='kol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
