# Generated by Django 2.2.4 on 2019-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
